_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 13
                - 16
                - 55
            "4": 3.9.6
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 8
effective_batch_size:
    value: 16
epochs:
    value: 3
learning_rate:
    value: 0.0002
lora_alpha:
    value: 32
lora_rank:
    value: 16
model:
    value: google/gemma-2b
